export const apiRoutes = {
  userInfo: "/user/info",
  userUpdate: "/user/info-update",
  userFeeds: "/user/feeds",
  likePost: "/post/like",
  unLikePost: "/post/unlike",
  userNotifications: "/notification/getall",
  userConnections: "/user/connections",
  userSignIn: "/auth/signin",
  userSignUp: "/auth/signup",
  userLogout: "/auth/logout",
  authCheck: "/auth/auth-check",
  userSearch: "/search/person",
  follow: "/connection/follow",
  unfollow: "/connection/unfollow",
  removeFollower: "/connection/removeFollower",
  testCookies: "/test-cookies",
  uploadPhotos: "/user/upload-post",
};
