export const urls = {
  root: "/",
  events: "events",
  about: "about",
  contact: "contact",
  signIn: "/signin",
  signUp: "signup",
  feeds: "feeds",
  profile: "user/:username",
  connections: "connections",
  notifications: "notifications",
  messages: "messages",
  search: "search",
  settings: "settings",
};
